
@token = {{telegramtoken}}
GET https://api.telegram.org/bot{{token}}/getMe

###
#ngrok test url
POST https://api.telegram.org/bot{{token}}/setwebhook 
content-type: application/json

{    
    "url": "https://fa6c505c.ngrok.io"
}