
@token = {{telegramtoken}}
GET https://api.telegram.org/bot{{token}}/getMe

###
#ngrok test url
POST https://api.telegram.org/bot{{token}}/setwebhook
content-type: application/json
{    
    "url": "https://6305121b.ngrok.io"
}


callback_data: JSON.stringify({
                            'command': 'label',
                            'area': 'development'
                        })
